version: "3.7"

services:
  back:
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./back:/code/back

  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./front:/app
      - /front/node_modules

  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111

volumes:
  postgres:
